name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install g++ and make
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make

      - name: Build with Make
        run: |
          make
          ./main

