on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up C++ toolchain
      uses: actions/setup-toolchain@v1
      with:
        toolchain: gcc

    - name: Build with Automake
      run: |
        aclocal
        autoconf
        automake --add-missing
        ./configure
        make
        make dist
