name: C++ AutoPackage CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper autoconf automake libtool

    - name: Regenerate autotools files
      run: |
        autoreconf -i

    - name: Build Debian Package
      run: |
        dpkg-buildpackage -us -uc

