name: Build and Test CI

on:
  push:
    branches:
      - branchAutoTest
  pull_request:
    branches:
      - branchAutoTest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          sudo apt-get install build-essential automake autoconf libtool libgtest-dev
      - name: Generate configuration files
        run: |
          autoreconf --install
      - name: Build and run tests
        run: |
          ./configure
          make
          make check

