name: C++ Automake CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up C++
      uses: actions/setup-cpp@v1
    - name: Build with Automake
      run: |
        aclocal
        autoconf
        automake --add-missing
        ./configure
        make
        make dist

