name: C++ AutoTest CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev cmake autoconf automake libtool
    - name: Build Google Test
      run: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp /usr/src/gtest/lib/*.a /usr/lib
    - name: Generate configuration files
      run: |
        aclocal
        autoconf
        automake --add-missing
    - name: Build and Run Tests
      run: |
        make check

