name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Autotools
        run: |
          sudo apt-get update
          sudo apt-get install -y automake autoconf dpkg-dev

      - name: Build with Makefile
        run: make

      - name: Build with Automake
        run: |
          autoreconf -i
          ./configure
          make dist

