name: C++ AutoTest CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up C++
      uses: actions/setup-cpp@v1
    - name: Install Google Test
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib
    - name: Build and Run Tests
      run: |
        make check

